services:
  postgres:
    image: postgres:18.3-alpine3.22
    restart: always
    shm_size: 128mb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    # - ./backend/db/scripts/:/docker-entrypoint-initdb.d # schema script

  pgadmin:
    image: dpage/pgadmin4:2026-03-03-1
    restart: always
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8000:80"
    volumes:
      # - ./backend/db/pgadmin/servers.json:/pgadmin4/servers.json
      # - ./backend/db/pgadmin/preferences.json:/pgadmin4/preferences.json
      # - ./backend/db/pgadmin/pgpass:/pgpass
      - pgadmin-data:/var/lib/pgadmin


volumes:
  pgdata:
  pgadmin-data:
  
