[project]
name = "joman"
version = "0.1.0"
description = "Sourashtra language dictionary backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.5",
    "fastapi>=0.116.1",
    "pydantic>=2.11.9",
    "sqlalchemy>=2.0.43",
]
