-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS dictionary.word
(
    word_id serial NOT NULL,
    text text NOT NULL,
    language_id integer NOT NULL,
    CONSTRAINT pk_word PRIMARY KEY (word_id)
);

COMMENT ON TABLE dictionary.word
    IS 'This is the written text of the word, and the building block of the entire system. ';

CREATE TABLE IF NOT EXISTS dictionary.language
(
    language_id serial NOT NULL,
    language character varying(10) NOT NULL,
    CONSTRAINT pk_language PRIMARY KEY (language_id)
);

CREATE TABLE IF NOT EXISTS dictionary.sentence
(
    sentence_id serial NOT NULL,
    text text NOT NULL,
    language_id integer,
    PRIMARY KEY (sentence_id)
);

CREATE TABLE IF NOT EXISTS dictionary.word_in_context
(
    word_id integer NOT NULL,
    sentence_id integer NOT NULL,
    PRIMARY KEY (word_id, sentence_id)
);

CREATE TABLE IF NOT EXISTS dictionary.category
(
    category_id serial NOT NULL,
    category text NOT NULL,
    PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS dictionary.word_category
(
    word_id integer NOT NULL,
    category_id integer NOT NULL,
    PRIMARY KEY (word_id, category_id)
);

CREATE TABLE IF NOT EXISTS dictionary.definition
(
    definition_id serial NOT NULL,
    word_id integer NOT NULL,
    text text NOT NULL,
    PRIMARY KEY (definition_id, word_id)
);

CREATE TABLE IF NOT EXISTS dictionary.translation
(
    this_word_id integer NOT NULL,
    other_word_id integer NOT NULL,
    PRIMARY KEY (this_word_id, other_word_id)
);

ALTER TABLE IF EXISTS dictionary.word
    ADD CONSTRAINT fk_word_language FOREIGN KEY (language_id)
    REFERENCES dictionary.language (language_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT fk_word_language ON dictionary.word
    IS 'map words to their language.';



ALTER TABLE IF EXISTS dictionary.sentence
    ADD CONSTRAINT fk_sentence_language FOREIGN KEY (language_id)
    REFERENCES dictionary.language (language_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS dictionary.word_in_context
    ADD CONSTRAINT fk_word FOREIGN KEY (word_id)
    REFERENCES dictionary.word (word_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dictionary.word_in_context
    ADD CONSTRAINT fk_sentence FOREIGN KEY (sentence_id)
    REFERENCES dictionary.sentence (sentence_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dictionary.word_category
    ADD CONSTRAINT fk_word FOREIGN KEY (word_id)
    REFERENCES dictionary.word (word_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dictionary.word_category
    ADD CONSTRAINT fk_category FOREIGN KEY (category_id)
    REFERENCES dictionary.category (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dictionary.definition
    ADD CONSTRAINT fk_word FOREIGN KEY (word_id)
    REFERENCES dictionary.word (word_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dictionary.translation
    ADD CONSTRAINT fk_this_word FOREIGN KEY (this_word_id)
    REFERENCES dictionary.word (word_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dictionary.translation
    ADD CONSTRAINT fk_other_word FOREIGN KEY (other_word_id)
    REFERENCES dictionary.word (word_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;