// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DictionaryCategory struct {
	CategoryID int32
	Category   string
}

type DictionaryLanguage struct {
	Language    string
	LanguageAlt pgtype.Text
}

type DictionaryPartOfSpeech struct {
	PartOfSpeech string
}

type DictionarySentence struct {
	SentenceID    int32
	SentenceText  string
	Language      string
	AudioFilePath pgtype.Text
}

type DictionarySentenceTranslation struct {
	SourashtraSentenceID int32
	OtherSentenceID      int32
}

type DictionaryTranslation struct {
	SourashtraWordID int32
	OtherWordID      int32
	Context          pgtype.Text
}

type DictionaryWord struct {
	WordID        int32
	WordText      string
	Language      string
	PartOfSpeech  string
	WordTextAlt   pgtype.Text
	AudioFilePath pgtype.Text
}

type DictionaryWordCategory struct {
	WordID     int32
	CategoryID int32
}

type DictionaryWordInContext struct {
	WordID     int32
	SentenceID int32
}
