// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CategoriesForWord(ctx context.Context, wordID int32) ([]CategoriesForWordRow, error)
}

var _ Querier = (*Queries)(nil)
