// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoriesForWord = `-- name: CategoriesForWord :many
select w.word_id,
       w.word_text,
       c.category,
       c.category_id
from dictionary.word w
inner join dictionary.word_category wc on w.word_id = wc.word_id
inner join dictionary.category c on c.category_id = wc.category_id
where w.word_id = $1
`

type CategoriesForWordRow struct {
	WordID     int32
	WordText   string
	Category   string
	CategoryID int32
}

func (q *Queries) CategoriesForWord(ctx context.Context, wordID int32) ([]CategoriesForWordRow, error) {
	rows, err := q.db.Query(ctx, categoriesForWord, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriesForWordRow
	for rows.Next() {
		var i CategoriesForWordRow
		if err := rows.Scan(
			&i.WordID,
			&i.WordText,
			&i.Category,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranslation = `-- name: GetTranslation :one
select sourashtra_word_id, other_word_id, context
from dictionary.translation
where sourashtra_word_id = $1
and   other_word_id = $2
`

type GetTranslationParams struct {
	SourashtraWordID int32
	OtherWordID      int32
}

func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (DictionaryTranslation, error) {
	row := q.db.QueryRow(ctx, getTranslation, arg.SourashtraWordID, arg.OtherWordID)
	var i DictionaryTranslation
	err := row.Scan(&i.SourashtraWordID, &i.OtherWordID, &i.Context)
	return i, err
}

const getWordCategory = `-- name: GetWordCategory :one
select word_id, category_id
from dictionary.word_category
where word_id = $1
and   category_id = $2
`

type GetWordCategoryParams struct {
	WordID     int32
	CategoryID int32
}

func (q *Queries) GetWordCategory(ctx context.Context, arg GetWordCategoryParams) (DictionaryWordCategory, error) {
	row := q.db.QueryRow(ctx, getWordCategory, arg.WordID, arg.CategoryID)
	var i DictionaryWordCategory
	err := row.Scan(&i.WordID, &i.CategoryID)
	return i, err
}

const getWordID = `-- name: GetWordID :one
select word_id
from dictionary.word
where word_text = $1
and   language = $2
`

type GetWordIDParams struct {
	WordText string
	Language string
}

func (q *Queries) GetWordID(ctx context.Context, arg GetWordIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getWordID, arg.WordText, arg.Language)
	var word_id int32
	err := row.Scan(&word_id)
	return word_id, err
}

const insertTranslation = `-- name: InsertTranslation :exec
insert into dictionary.translation (sourashtra_word_id, other_word_id, context)
values ($1, $2, $3)
`

type InsertTranslationParams struct {
	SourashtraWordID int32
	OtherWordID      int32
	Context          pgtype.Text
}

func (q *Queries) InsertTranslation(ctx context.Context, arg InsertTranslationParams) error {
	_, err := q.db.Exec(ctx, insertTranslation, arg.SourashtraWordID, arg.OtherWordID, arg.Context)
	return err
}

const insertWord = `-- name: InsertWord :one
insert into dictionary.word (word_text, language, part_of_speech, word_text_alt)
values ($1, $2, $3, $4)
returning word_id
`

type InsertWordParams struct {
	WordText     string
	Language     string
	PartOfSpeech string
	WordTextAlt  pgtype.Text
}

func (q *Queries) InsertWord(ctx context.Context, arg InsertWordParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertWord,
		arg.WordText,
		arg.Language,
		arg.PartOfSpeech,
		arg.WordTextAlt,
	)
	var word_id int32
	err := row.Scan(&word_id)
	return word_id, err
}

const insertWordCategory = `-- name: InsertWordCategory :exec
insert into dictionary.word_category (word_id, category_id)
values ($1, $2)
`

type InsertWordCategoryParams struct {
	WordID     int32
	CategoryID int32
}

func (q *Queries) InsertWordCategory(ctx context.Context, arg InsertWordCategoryParams) error {
	_, err := q.db.Exec(ctx, insertWordCategory, arg.WordID, arg.CategoryID)
	return err
}

const listCategories = `-- name: ListCategories :many
select category_id, 
       category
from dictionary.category
order by category
`

func (q *Queries) ListCategories(ctx context.Context) ([]DictionaryCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DictionaryCategory
	for rows.Next() {
		var i DictionaryCategory
		if err := rows.Scan(&i.CategoryID, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sentencesForWord = `-- name: SentencesForWord :many
select w.word_id,
       w.word_text,
       s.sentence_id,
       s.sentence_text
from dictionary.word w
inner join dictionary.word_in_context sw on w.word_id = sw.word_id
inner join dictionary.sentence s on sw.sentence_id = s.sentence_id
where w.word_id = $1
`

type SentencesForWordRow struct {
	WordID       int32
	WordText     string
	SentenceID   int32
	SentenceText string
}

func (q *Queries) SentencesForWord(ctx context.Context, wordID int32) ([]SentencesForWordRow, error) {
	rows, err := q.db.Query(ctx, sentencesForWord, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SentencesForWordRow
	for rows.Next() {
		var i SentencesForWordRow
		if err := rows.Scan(
			&i.WordID,
			&i.WordText,
			&i.SentenceID,
			&i.SentenceText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sourashtraTranslation = `-- name: SourashtraTranslation :many
with sourashtra as (
    select word_id as sourashtra_word_id, 
           word_text as sourashtra_text, 
           part_of_speech,
           word_text_alt as sourashtra_text_alt
    from dictionary.word
    where dictionary.word.word_id = $1
    and language = 'Sourashtra'
),
other as (
    select word_id as target_word_id, 
           word_text as target_word_text, 
           word_text_alt as target_text_alt,
           language as target_language
    from dictionary.word 
    where language != 'Sourashtra'
)
select sourashtra.sourashtra_word_id, sourashtra.sourashtra_text, sourashtra.part_of_speech, sourashtra.sourashtra_text_alt,
       other.target_word_id, other.target_word_text, other.target_text_alt, other.target_language,
       translation.context
from sourashtra 
inner join dictionary.translation
on   sourashtra.sourashtra_word_id = translation.sourashtra_word_id
inner join other
on   translation.target_word_id = other.target_word_id
`

type SourashtraTranslationRow struct {
	SourashtraWordID  int32
	SourashtraText    string
	PartOfSpeech      string
	SourashtraTextAlt pgtype.Text
	TargetWordID      int32
	TargetWordText    string
	TargetTextAlt     pgtype.Text
	TargetLanguage    string
	Context           pgtype.Text
}

func (q *Queries) SourashtraTranslation(ctx context.Context, wordID int32) ([]SourashtraTranslationRow, error) {
	rows, err := q.db.Query(ctx, sourashtraTranslation, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourashtraTranslationRow
	for rows.Next() {
		var i SourashtraTranslationRow
		if err := rows.Scan(
			&i.SourashtraWordID,
			&i.SourashtraText,
			&i.PartOfSpeech,
			&i.SourashtraTextAlt,
			&i.TargetWordID,
			&i.TargetWordText,
			&i.TargetTextAlt,
			&i.TargetLanguage,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const translationToSourashtra = `-- name: TranslationToSourashtra :many
with other as (
    select word_id as source_word_id, 
           word_text as source_word_text, 
           part_of_speech,
           language as source_language
    from dictionary.word 
    where dictionary.word.word_id = $1
),
sourashtra as (
    select word_id as sourashtra_word_id, 
           word_text as sourashtra_text
    from dictionary.word
    where language = 'Sourashtra'
)
select sourashtra.sourashtra_word_id, sourashtra.sourashtra_text,
       other.source_word_id, other.source_word_text, other.part_of_speech, other.source_language,
       translation.context
from sourashtra 
inner join dictionary.translation
on   sourashtra.sourashtra_word_id = translation.sourashtra_word_id
inner join other
on   translation.target_word_id = other.target_word_id
`

type TranslationToSourashtraRow struct {
	SourashtraWordID int32
	SourashtraText   string
	SourceWordID     int32
	SourceWordText   string
	PartOfSpeech     string
	SourceLanguage   string
	Context          pgtype.Text
}

func (q *Queries) TranslationToSourashtra(ctx context.Context, wordID int32) ([]TranslationToSourashtraRow, error) {
	rows, err := q.db.Query(ctx, translationToSourashtra, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationToSourashtraRow
	for rows.Next() {
		var i TranslationToSourashtraRow
		if err := rows.Scan(
			&i.SourashtraWordID,
			&i.SourashtraText,
			&i.SourceWordID,
			&i.SourceWordText,
			&i.PartOfSpeech,
			&i.SourceLanguage,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const translationsForCategory = `-- name: TranslationsForCategory :many
with sourashtra as (
    select w.word_id as sourashtra_word_id,
           w.word_text as sourashtra_text,
           w.part_of_speech,
           w.word_text_alt as sourashtra_text_alt
    from dictionary.word w
    inner join dictionary.word_category wc on w.word_id = wc.word_id
    where wc.category_id = $1
    and w.language = 'Sourashtra'
),
other as (
    select word_id as target_word_id,
           word_text as target_word_text,
           word_text_alt as target_text_alt,
           language as target_language
    from dictionary.word
    where language != 'Sourashtra'
)
select sourashtra.sourashtra_word_id, sourashtra.sourashtra_text, sourashtra.part_of_speech, sourashtra.sourashtra_text_alt,
       other.target_word_id, other.target_word_text, other.target_text_alt, other.target_language,
       translation.context
from sourashtra
inner join dictionary.translation on sourashtra.sourashtra_word_id = translation.sourashtra_word_id
inner join other on translation.other_word_id = other.target_word_id
`

type TranslationsForCategoryRow struct {
	SourashtraWordID  int32
	SourashtraText    string
	PartOfSpeech      string
	SourashtraTextAlt pgtype.Text
	TargetWordID      int32
	TargetWordText    string
	TargetTextAlt     pgtype.Text
	TargetLanguage    string
	Context           pgtype.Text
}

func (q *Queries) TranslationsForCategory(ctx context.Context, categoryID int32) ([]TranslationsForCategoryRow, error) {
	rows, err := q.db.Query(ctx, translationsForCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TranslationsForCategoryRow
	for rows.Next() {
		var i TranslationsForCategoryRow
		if err := rows.Scan(
			&i.SourashtraWordID,
			&i.SourashtraText,
			&i.PartOfSpeech,
			&i.SourashtraTextAlt,
			&i.TargetWordID,
			&i.TargetWordText,
			&i.TargetTextAlt,
			&i.TargetLanguage,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wordSearch = `-- name: WordSearch :many
select word_id,
       word_text,
       part_of_speech,
       word_text_alt,
       similarity(word_text, $2) as score
from dictionary.word
where language = $1
and   (word_text % $2 or word_text_alt % $2) 
order by score desc
`

type WordSearchParams struct {
	Language   string
	Similarity string
}

type WordSearchRow struct {
	WordID       int32
	WordText     string
	PartOfSpeech string
	WordTextAlt  pgtype.Text
	Score        float32
}

func (q *Queries) WordSearch(ctx context.Context, arg WordSearchParams) ([]WordSearchRow, error) {
	rows, err := q.db.Query(ctx, wordSearch, arg.Language, arg.Similarity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WordSearchRow
	for rows.Next() {
		var i WordSearchRow
		if err := rows.Scan(
			&i.WordID,
			&i.WordText,
			&i.PartOfSpeech,
			&i.WordTextAlt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wordsForSentence = `-- name: WordsForSentence :many
select s.sentence_id,
       s.sentence_text,
       w.word_id,
       w.word_text
from dictionary.sentence s
inner join dictionary.word_in_context wc on s.sentence_id = wc.sentence_id
inner join dictionary.word w on wc.word_id = w.word_id
where s.sentence_id = $1
`

type WordsForSentenceRow struct {
	SentenceID   int32
	SentenceText string
	WordID       int32
	WordText     string
}

func (q *Queries) WordsForSentence(ctx context.Context, sentenceID int32) ([]WordsForSentenceRow, error) {
	rows, err := q.db.Query(ctx, wordsForSentence, sentenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WordsForSentenceRow
	for rows.Next() {
		var i WordsForSentenceRow
		if err := rows.Scan(
			&i.SentenceID,
			&i.SentenceText,
			&i.WordID,
			&i.WordText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
