// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"
)

type Querier interface {
	CategoriesForWord(ctx context.Context, wordID int32) ([]CategoriesForWordRow, error)
	InsertTranslation(ctx context.Context, arg InsertTranslationParams) error
	InsertWord(ctx context.Context, arg InsertWordParams) (int32, error)
	InsertWordCategory(ctx context.Context, arg InsertWordCategoryParams) error
	ListCategories(ctx context.Context) ([]DictionaryCategory, error)
	SentencesForWord(ctx context.Context, wordID int32) ([]SentencesForWordRow, error)
	SourashtraTranslation(ctx context.Context, wordID int32) ([]SourashtraTranslationRow, error)
	TranslationToSourashtra(ctx context.Context, wordID int32) ([]TranslationToSourashtraRow, error)
	TranslationsForCategory(ctx context.Context, categoryID int32) ([]TranslationsForCategoryRow, error)
	WordSearch(ctx context.Context, arg WordSearchParams) ([]WordSearchRow, error)
	WordsForSentence(ctx context.Context, sentenceID int32) ([]WordsForSentenceRow, error)
}

var _ Querier = (*Queries)(nil)
