// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sqlc-queries.sql

package repository

import (
	"context"
)

const categoriesForWord = `-- name: CategoriesForWord :many
select w.word_id,
       w.word_text,
       c.category
from dictionary.word w
inner join dictionary.word_category wc on w.word_id = wc.word_id
inner join dictionary.category c on c.category_id = wc.category_id
where w.word_id = $1
`

type CategoriesForWordRow struct {
	WordID   int32
	WordText string
	Category string
}

func (q *Queries) CategoriesForWord(ctx context.Context, wordID int32) ([]CategoriesForWordRow, error) {
	rows, err := q.db.Query(ctx, categoriesForWord, wordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriesForWordRow
	for rows.Next() {
		var i CategoriesForWordRow
		if err := rows.Scan(&i.WordID, &i.WordText, &i.Category); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
